server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/account_service/**
          filters:
            - StripPrefix=2

        - id: order_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/order_service/**
          filters:
            - StripPrefix=2

        - id: other_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/other_service/**
          filters:
            - StripPrefix=2