server:
  port: 8082
  servlet:
    context-path: /other_service


spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/FoodApp?authSource=admin


models:
  openRouter:
    url: https://openrouter.ai/api/v1
    key: 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

chatbot:
  url: "${models.openRouter.url}"
  key: "${models.openRouter.key}"