server:
  port: 8080
  servlet:
    context-path: /account_service


spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://root:root@localhost:3306/FoodApp}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
  jpa:
    hibernate:
      ddl-auto: update


key:
  value: ${KEY_JWT}

app:
  services:
    cart: ${CART_URL:http://localhost:8081}/order_service/cart
    notification: ${NOTIFICATION_URL:http://localhost:8083}/notification_service

  time:
    otp: 1

