server:
  port: 8080
  servlet:
    context-path: /account_service

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FoodApp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379

key:
  value:

app:
  services:
    cart: http://localhost:8081/order_service/cart
    notification: http://localhost:8083/notification_service

  time:
    otp: 1