server:
  port: 8083
  servlet:
    context-path: /notification_service

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/FoodApp?authSource=admin

app:
  service:
    account: http://localhost:8080/account_service

  client:
    smtp: https://api.brevo.com/v3/smtp
    contact:
      name: Food App
      email: 2251160057@ut.edu.vn




key:
  jwt:
  email: