server:
  port: 8083
  servlet:
    context-path: /notification_service

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/FoodApp?authSource=admin

app:
  service:
    account: http://localhost:8080/account_service

key:
  jwt: this-is-a-very-long-secret-key-32-characters