server:
  port: 8081
  servlet:
    context-path: /order_service


spring:
  data:
    mongodb:
      uri: mongodb+srv://letan:root@cluster0.6tbmrfq.mongodb.net/FoodApp?retryWrites=true&w=majority&appName=Cluster0&sslInvalidHostNameAllowed=true&tlsAllowInvalidCertificates=true

app:
  service:
    account: ${ACCOUNT_URL:http://localhost:8080}/account_service

key:
  jwt: ${KEY_JWT}

