server:
  port: 8081
  servlet:
    context-path: /order_service


spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/FoodApp?authSource=admin

key:
  value: this-is-a-very-long-secret-key-32-characters